version: '3.7'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/app
    container_name: book-chat-nginx
    restart: always
    ports:
      - '8089:80'
      - '2446:2446'

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/app
    container_name: book-chat-php
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    container_name: book-chat-mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=ro"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - '33339:80'
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 4953500000 kb


volumes:
  mysql: